### PR TITLE
Addresses bug in setpoint_humidistat_object

### PR DESCRIPTION
**Pull request by tanushree04**
@chriswmackey This PR includes fixing the bug in the humidistat object and implenting reordering of vertices for aperture, door, shade objects as well.

### CODE REVIEW

**Comment by chriswmackey** [comment]
@tanushree04 ,

I actually uncovered that this was a part of a few other bugs/typos back in the honeybee_schema repo. If you don't mind, I have a PR prepared that not only fixes this but also updates the incorrect OpenAPI schema definition.

**Comment by chriswmackey** [comment]
This is the other PR: https://github.com/ladybug-tools-in2/energy-model-measure/pull/71

Let me merge it in and then we'll close out this one. I promise that I'll stop sending edits after we merge it in if you want to keep committing more changes.

Also, it looks like you should rebase your fork if you send any PRs after this one.

**Comment by chriswmackey** [comment]
I'll close this and then you should rebase your fork.

**Comment by tanushree04** [comment]
@chriswmackey I have rebased my fork.

**Comment by chriswmackey** [comment]
Thank you, @tanushree04 . Now that most of the critical issues have been fixed with the last PRs that you and I sent, the remaining issues aren't at as high of a priority. If you have time, [it would be good to tackle this issue aimed at improving the tests](https://github.com/ladybug-tools-in2/energy-model-measure/issues/72) but I definitely understand if you'd like to take that one at a slower pace.

**Pull request closed without merging**
